CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username Encod(50) NOT NULL UNIQUE,
    password emcoco(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);